# fly.toml app configuration file generated for alby-jim on 2024-08-17T12:39:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alby-jim'
primary_region = 'lax'
swap_size_mb = 512

[build]

[[mounts]]
  source = 'jim_data'
  destination = '/data'
  initial_size = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512
